name: Java CI|CD with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582

      - name: Grant execute permission for Gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle Wrapper
        run: ./gradlew clean build

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: java-app
          path: build/libs/*.jar

  release:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' || github.event_name == 'pull_request'
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.TOKEN }}

      - name: Download Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: java-app

      - name: Generate Version Tag
        id: generate_tag
        run: |
          APP_VERSION=$(grep '^app.version=' src/main/resources/application.properties | cut -d'=' -f2)
          TAG="v-${APP_VERSION}"
          echo "tag=${TAG}" >> $GITHUB_ENV

      - name: Create Tag
        run: |
          git tag ${{ env.tag }}
          git push origin ${{ env.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: java-app/*.jar
          tag_name: ${{ env.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
