name: Java CI|CD with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Grant execute permission for Gradlew
        run: chmod +x ./gradlew

      - name: Build and Test with Gradle
        run: ./gradlew clean build test  # Ensures code is compiled and tested

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: build/libs/*.jar

      - name: Build & Push Docker Image
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: sankalana98/springboot-github-actions-tutorial
          tags: latest
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

  release:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.TOKEN }}

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Download Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: build-artifact

      - name: Generate Version Tag
        id: generate_tag
        run: |
          APP_VERSION=$(grep '^app.version=' src/main/resources/application.properties | cut -d'=' -f2)
          TAG="v-${APP_VERSION}"
          echo "tag=${TAG}" >> $GITHUB_ENV

      - name: Create Tag
        run: |
          git tag ${{ env.tag }}
          git push origin ${{ env.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/libs/*.jar
          tag_name: ${{ env.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
